### ISSUE TITLE
Train NVS networks with estimated pose

### ISSUE THREAD

**Issue by crepejung00** [ffrivera0/reloc3r#1]
Hi,
thanks for the great work!

I am looking forward to checking out your code when released :)
In the meantime, I wonder if your work can be used to accelerate the whole process of estimating relative poses with the dust3r framework such as, having 1000 images in total select 10 frames to run dust3r with global alignment to estimate camera poses. With the camera poses of 10 frames locate the camera poses of the remaining 990 images.

Would this kind of approach be possible and effective?

Thanks!

**Comment by ffrivera0** [comment]
Thank you for your interest in our work! While we haven't tested this specific approach, it should be feasible.

You’ll need to choose an appropriate number of images for the DUSt3R reconstruction, ensuring they cover the entire scene and have sufficient overlap with the remaining images. After that, you can do the image registration(relocalization) for the remaining images with Reloc3r. 

We hope this helps, and please stay tuned for our code release!

**Comment by crepejung00** [comment]
Okay, that makes sense.
I will try when the code is ready!

Thanks for the great work and reply!
